# Generated by Django 6.1 on 2026-08-24 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_date_naissance_user_matricule_user_pays_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('conge', 'En congé'), ('inactif', 'Inactif')], default='actif', max_length=20),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams_managed', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='accounts.organisation')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('organisation', 'code')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='accounts.team'),
        ),
    ]
