# Generated by Django 6.1 on 2026-08-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_statut_team_user_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='autre_piece_document',
            field=models.ImageField(blank=True, null=True, upload_to='documents/autres/'),
        ),
        migrations.AddField(
            model_name='user',
            name='cni_document',
            field=models.ImageField(blank=True, null=True, upload_to='documents/cni/'),
        ),
    ]
