# Generated by Django 6.1 on 2026-08-25 09:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_autre_piece_document_user_cni_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assurance_sante',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='banque',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='cnps',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='competences_principales',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='competences_secondaires',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='compte_bancaire',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='contact_urgence_nom',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='contact_urgence_telephone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='contrat_document',
            field=models.FileField(blank=True, null=True, upload_to='documents/contrats/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AddField(
            model_name='user',
            name='contribuable',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='cv_document',
            field=models.FileField(blank=True, null=True, upload_to='documents/cv/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AddField(
            model_name='user',
            name='date_embauche',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='departement',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='groupe_sanguin',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='horaire',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='lieu_travail',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='periode_essai',
            field=models.CharField(blank=True, choices=[('en_cours', 'En cours'), ('terminee', 'Terminée')], max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='responsable_hierarchique',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='temps_travail',
            field=models.CharField(blank=True, choices=[('temps_plein', 'Temps plein'), ('temps_partiel', 'Temps partiel')], max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='type_contrat',
            field=models.CharField(blank=True, choices=[('cdi', 'CDI'), ('cdd', 'CDD'), ('stage', 'Stage'), ('alternance', 'Alternance'), ('consultant', 'Consultant')], max_length=20),
        ),
    ]
