# Generated by Django 6.1 on 2026-08-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_assurance_sante_user_banque_user_cnps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
