# Generated by Django 6.1 on 2026-08-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='departement',
        ),
        migrations.RemoveField(
            model_name='user',
            name='horaire',
        ),
        migrations.RemoveField(
            model_name='user',
            name='responsable_hierarchique',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='documents/photos/'),
        ),
    ]
