# Generated by Django 6.1 on 2026-08-25 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_user_departement_remove_user_horaire_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='lieu_travail',
        ),
    ]
