# Generated by Django 6.1 on 2026-08-26 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_affectationhistory_gradehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_protected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_teams', to='accounts.team'),
        ),
    ]
