# Generated by Django 6.1 on 2026-08-26 17:30

from django.db import migrations, models

DEFAULT_TEAM_LEVELS = {'DG': 1, 'PIL': 2, 'RES': 3}


def set_default_team_levels(apps, schema_editor):
    Team = apps.get_model('accounts', 'Team')
    for code, niveau in DEFAULT_TEAM_LEVELS.items():
        Team.objects.filter(is_protected=True, code=code).update(niveau=niveau)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_team_is_protected_team_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='parent',
        ),
        migrations.AddField(
            model_name='organisation',
            name='team_levels_count',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='team',
            name='niveau',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.RunPython(set_default_team_levels, noop),
    ]
