# Generated by Django 6.1 on 2026-08-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_avancedemande_congedemande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avancedemande',
            name='motif',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='congedemande',
            name='motif',
            field=models.TextField(blank=True),
        ),
    ]
