# Generated by Django 6.1 on 2026-08-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_avancedemande_motif_alter_congedemande_motif'),
    ]

    operations = [
        migrations.AddField(
            model_name='congedemande',
            name='cloture',
            field=models.BooleanField(default=False),
        ),
    ]
