# Generated by Django 6.1 on 2026-08-27 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_finalize_type_conge_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='congedemande',
            name='demi_journee_debut',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='congedemande',
            name='demi_journee_fin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='congetype',
            name='categorie',
            field=models.CharField(choices=[('standard', 'Standard'), ('maladie', 'Congé maladie'), ('technique', 'Congé technique')], default='standard', max_length=10),
        ),
        migrations.AddField(
            model_name='congetype',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='congetype',
            name='jours_alloues',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='congetype',
            name='mode_periode',
            field=models.CharField(blank=True, choices=[('employe', 'Le salarié choisit la période'), ('entreprise', "L'entreprise définit la période")], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='congetype',
            name='unite',
            field=models.CharField(blank=True, choices=[('mois', 'Par mois'), ('annee', 'Par année')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='FermetureTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employes_exceptes', models.ManyToManyField(blank=True, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('equipes_exceptees', models.ManyToManyField(blank=True, related_name='+', to='accounts.team')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fermetures_techniques', to='accounts.organisation')),
            ],
            options={
                'ordering': ['-date_debut'],
            },
        ),
    ]
