# Generated by Django 6.1 on 2026-08-27 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_backfill_default_conge_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='conge_technique_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes_places_en_conge', to='accounts.fermeturetechnique'),
        ),
    ]
