# Generated by Django 6.1 on 2026-08-28 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_conge_technique_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='LigneBudgetaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('nom', models.CharField(max_length=200)),
                ('niveau', models.PositiveSmallIntegerField()),
                ('declinaison', models.CharField(blank=True, max_length=255)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_budgetaires', to='accounts.team')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_budgetaires', to='accounts.organisation')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enfants', to='accounts.lignebudgetaire')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('organisation', 'code')},
            },
        ),
    ]
