# Generated by Django 6.1 on 2026-08-28 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_ligne_budgetaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('nom', models.CharField(max_length=255)),
                ('client', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('type_montant', models.CharField(choices=[('HT', 'HT'), ('TTC', 'TTC')], default='HT', max_length=5)),
                ('marge_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('charges_transversales_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tva_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ir_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('reserve_montant', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('definitif', 'Définitif')], default='brouillon', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='accounts.organisation')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('organisation', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ProjectLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('nom', models.CharField(max_length=255)),
                ('type_ligne', models.CharField(choices=[('E', 'EHS'), ('D', 'Monétaire')], default='E', max_length=1)),
                ('division', models.CharField(blank=True, max_length=150)),
                ('ehs', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('attribue_a', models.CharField(blank=True, max_length=150)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='accounts.project')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('project', 'code')},
            },
        ),
    ]
