# Generated by Django 6.1 on 2026-08-28 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_project_ligne_budgetaire_attribution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectligne',
            name='attribue_a',
        ),
    ]
