# Generated by Django 6.1 on 2026-08-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='date_debut',
        ),
        migrations.RemoveField(
            model_name='task',
            name='date_fin',
        ),
        migrations.AddField(
            model_name='task',
            name='heures',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
