# Generated by Django 6.1 on 2026-08-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_task_heures'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='lancee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='lancee_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
