# Generated by Django 6.1 on 2026-08-31 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_task_template_equipe_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='demarree_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='execution_statut',
            field=models.CharField(choices=[('a_demarrer', 'À démarrer'), ('en_cours', 'En cours'), ('en_pause', 'En pause'), ('terminee', 'Terminée')], default='a_demarrer', max_length=12),
        ),
        migrations.AddField(
            model_name='task',
            name='terminee_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
