# Generated by Django 6.1 on 2026-08-31 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_finalize_task_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='country_code',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='organisation',
            name='currency_code',
            field=models.CharField(default='XAF', max_length=3),
        ),
        migrations.AddField(
            model_name='user',
            name='pays_code',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('recurrente_annuelle', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_holidays', to='accounts.organisation')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('organisation', 'date', 'nom')},
            },
        ),
    ]
