# Generated by Django 6.1 on 2026-09-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_organisation_country_code_organisation_currency_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicholiday',
            name='source',
            field=models.CharField(choices=[('auto', 'Automatique'), ('manuel', 'Manuel')], default='manuel', max_length=10),
        ),
    ]
