# Generated by Django 6.1 on 2026-09-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_team_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassignment',
            name='temps_travaille_secondes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
