# Generated by Django 6.1 on 2026-09-01 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_taskassignment_temps_travaille_secondes'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassignment',
            name='note',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='note_commentaire',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='notee_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='notee_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
