# Generated by Django 6.1 on 2026-09-03 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_participants_forward(apps, schema_editor):
    """Conversation passe de deux colonnes FK (participant_1/participant_2) à un M2M
    `participants` pour permettre les discussions de groupe — cette étape reporte les paires déjà
    existantes dans le nouveau M2M avant que les anciennes colonnes ne soient supprimées, pour ne
    perdre aucune conversation déjà en cours."""
    Conversation = apps.get_model('accounts', 'Conversation')
    for conversation in Conversation.objects.all():
        conversation.participants.set([conversation.participant_1_id, conversation.participant_2_id])


def migrate_participants_backward(apps, schema_editor):
    """Sens inverse (au cas où) : reconstitue participant_1/participant_2 à partir du M2M pour les
    conversations 1:1 — les groupes (plus de 2 participants) ne peuvent pas être reconvertis et
    sont ignorés, cette direction n'étant utile qu'en cas de rollback avant la création d'un
    premier groupe."""
    Conversation = apps.get_model('accounts', 'Conversation')
    for conversation in Conversation.objects.all():
        ids = sorted(conversation.participants.values_list('id', flat=True))
        if len(ids) == 2:
            conversation.participant_1_id, conversation.participant_2_id = ids
            conversation.save(update_fields=['participant_1_id', 'participant_2_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_taskmessage_attachment_taskmessage_attachment_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='conversation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='nom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='conversation',
            name='participants',
            field=models.ManyToManyField(related_name='conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(migrate_participants_forward, migrate_participants_backward),
        migrations.AddField(
            model_name='directmessage',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskmessage',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='participant_1',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='participant_2',
        ),
        migrations.CreateModel(
            name='TypingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('task', 'Tâche'), ('conversation', 'Conversation')], max_length=12)),
                ('scope_id', models.PositiveIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('scope', 'scope_id', 'user')},
            },
        ),
    ]
