# Generated by Django 6.1 on 2026-09-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_alter_congetype_jours_alloues_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='congetype',
            name='cumul_en_avance',
            field=models.BooleanField(default=False),
        ),
    ]
