# Generated by Django 6.1 on 2026-09-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_congetype_cumul_en_avance'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='taux_grade_fcfa',
            field=models.DecimalField(decimal_places=2, default=25000, max_digits=10),
        ),
    ]
