# Generated by Django 6.1 on 2026-09-08 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_organisation_taux_charges_sociales_pct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fournisseur', models.CharField(blank=True, max_length=255)),
                ('type_depense', models.CharField(blank=True, choices=[('Transversal', 'Transversal'), ('Non Transversal', 'Non Transversal')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('devise', models.CharField(max_length=3)),
                ('date_depense', models.DateField(blank=True, null=True)),
                ('objet', models.TextField(blank=True)),
                ('commentaires', models.CharField(blank=True, max_length=500)),
                ('mode_paiement', models.CharField(blank=True, choices=[('Virement bancaire', 'Virement bancaire'), ('Mobile Money', 'Mobile Money'), ('Espèces', 'Espèces'), ('Chèque', 'Chèque')], max_length=40)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('attente', 'En attente d’exécution'), ('execute', 'Exécuté (Accepté)'), ('refuse', 'Refusé')], default='brouillon', max_length=12)),
                ('commentaire_execution', models.TextField(blank=True)),
                ('justificatif', models.FileField(blank=True, upload_to='paiements/%Y/%m/')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ligne_budgetaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.lignebudgetaire')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organisation')),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.project')),
            ],
            options={
                'ordering': ['-updated_at', '-pk'],
            },
        ),
    ]
