# Generated by Django 6.1 on 2026-09-08 13:44

from decimal import Decimal

from django.db import migrations, models

TRANSVERSAL_LIGNE_CODE = 'TRANSV'
TRANSVERSAL_LIGNE_PART = Decimal('0.10')


def seed_transversal_lignes(apps, schema_editor):
    """Pour chaque organisation : crée la ligne budgétaire « Charges transversales » (Ressources)
    si absente, puis l'attribue à chaque projet existant à hauteur de 10 % du montant."""
    Organisation = apps.get_model('accounts', 'Organisation')
    Team = apps.get_model('accounts', 'Team')
    LigneBudgetaire = apps.get_model('accounts', 'LigneBudgetaire')
    Project = apps.get_model('accounts', 'Project')
    ProjectLigne = apps.get_model('accounts', 'ProjectLigne')

    for organisation in Organisation.objects.all():
        ligne = LigneBudgetaire.objects.filter(organisation=organisation, code=TRANSVERSAL_LIGNE_CODE).first()
        if ligne is None:
            equipe = (
                Team.objects.filter(organisation=organisation, code='RES').first()
                or Team.objects.filter(organisation=organisation, is_protected=True).order_by('-niveau').first()
                or Team.objects.filter(organisation=organisation).order_by('niveau').first()
            )
            if equipe is None:
                continue
            ligne = LigneBudgetaire.objects.create(
                organisation=organisation, code=TRANSVERSAL_LIGNE_CODE, nom='Charges transversales',
                niveau=1, equipe=equipe, is_transversale=True, actif=True,
            )
        else:
            LigneBudgetaire.objects.filter(pk=ligne.pk).update(is_transversale=True)

        for project in Project.objects.filter(organisation=organisation):
            if ProjectLigne.objects.filter(project=project, is_transversale=True).exists():
                continue
            if ProjectLigne.objects.filter(project=project, ligne_budgetaire=ligne).exists():
                continue
            montant = (project.montant * TRANSVERSAL_LIGNE_PART).quantize(Decimal('0.01'))
            code = f'PRJ.{str(ProjectLigne.objects.filter(project=project).count() + 1).zfill(3)}'
            ProjectLigne.objects.create(
                project=project, code=code, ligne_budgetaire=ligne, montant=montant,
                is_transversale=True, montant_auto=True,
            )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0054_demandepaiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignebudgetaire',
            name='is_transversale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectligne',
            name='is_transversale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectligne',
            name='montant_auto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='date_debut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunPython(seed_transversal_lignes, noop),
    ]
