# Generated by Django 6.1 on 2026-09-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_lignebudgetaire_is_transversale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='cible_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='cible_type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
