# Generated by Django 6.1 on 2026-09-15, hand-adjusted: `ville` (région, mal nommé) devient
# `region` (RenameField, préserve les données existantes) et un vrai `ville` (ville précise,
# vide au départ) est ajouté séparément. Lieu de résidence = ville, région, pays.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_notification_cible_id_notification_cible_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='ville',
            new_name='region',
        ),
        migrations.AddField(
            model_name='user',
            name='ville',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
