# Generated by Django 6.1 on 2026-09-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0057_user_region_alter_user_ville'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sexe',
            field=models.CharField(blank=True, choices=[('M', 'Homme'), ('F', 'Femme')], max_length=1),
        ),
    ]
