# Generated by Django 6.1 on 2026-09-16 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0058_user_sexe'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_grade', models.PositiveIntegerField()),
                ('nouveau_grade', models.PositiveIntegerField()),
                ('motif', models.TextField()),
                ('statut', models.CharField(choices=[('attente', 'En attente'), ('approuvee', 'Approuvée'), ('refusee', 'Refusée')], default='attente', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('commentaire_revue', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_change_requests', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatutHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_statut', models.CharField(choices=[('actif', 'Actif'), ('conge', 'En congé'), ('inactif', 'Inactif')], max_length=20)),
                ('nouveau_statut', models.CharField(choices=[('actif', 'Actif'), ('conge', 'En congé'), ('inactif', 'Inactif')], max_length=20)),
                ('motif', models.CharField(blank=True, max_length=255)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statut_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Statut histories',
                'ordering': ['-changed_at'],
            },
        ),
    ]
