# Generated by Django 6.1 on 2026-09-16 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0060_avancedemande_code_congedemande_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='congedemande',
            name='delegue_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conge_delegations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='congedemande',
            name='disponibilite_confirmee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='congedemande',
            name='disponibilite_confirmee_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='congedemande',
            name='pilotage_alerte_envoyee',
            field=models.BooleanField(default=False),
        ),
    ]
