# Generated by Django 6.1 on 2026-09-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0061_congedemande_delegue_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='taux_tva_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
