# Generated by Django 6.1 on 2026-09-17 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0062_organisation_taux_tva_pct'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectligne',
            unique_together={('project', 'code'), ('project', 'ligne_budgetaire')},
        ),
        migrations.AddField(
            model_name='projectligne',
            name='task_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_lignes', to='accounts.tasktemplate'),
        ),
        migrations.AddField(
            model_name='projectligne',
            name='type_ligne',
            field=models.CharField(choices=[('M', 'Monétaire'), ('E', 'EHS')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='projectligne',
            name='ligne_budgetaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_lignes', to='accounts.lignebudgetaire'),
        ),
        migrations.AlterUniqueTogether(
            name='projectligne',
            unique_together={('project', 'code'), ('project', 'ligne_budgetaire'), ('project', 'task_template')},
        ),
    ]
