# Generated by Django 6.1 on 2026-09-17 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0063_alter_projectligne_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attributions', to='accounts.tasktemplate'),
        ),
    ]
