# Generated by Django 6.1 on 2026-09-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0064_alter_task_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassignment',
            name='instructions',
            field=models.TextField(blank=True),
        ),
    ]
