# Generated by Django 6.1 on 2026-09-23 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0065_taskassignment_instructions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskmessage',
            options={'ordering': ['created_at', 'id']},
        ),
        migrations.AddField(
            model_name='taskmessage',
            name='est_systeme',
            field=models.BooleanField(default=False),
        ),
    ]
