# Generated by Django 6.1 on 2026-09-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0066_taskmessage_est_systeme'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='revue_override',
            field=models.CharField(blank=True, choices=[('en_cours', 'En cours'), ('termine', 'Terminée')], max_length=10),
        ),
    ]
