# Generated by Django 6.1 on 2026-10-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0067_task_revue_override'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='revue_override',
            field=models.CharField(blank=True, choices=[('en_cours', 'En cours'), ('en_revue', 'En revue'), ('termine', 'Terminée')], max_length=10),
        ),
    ]
