# Generated by Django 6.1 on 2026-10-02 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0068_alter_task_revue_override'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskmessage',
            options={'ordering': ['created_at', 'id']},
        ),
    ]
