# Generated by Django 6.1 on 2026-10-05 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0069_alter_taskmessage_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteTresorerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=30)),
                ('sous_libelle', models.CharField(blank=True, max_length=100)),
                ('solde_initial', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptes_tresorerie', to='accounts.organisation')),
            ],
            options={
                'ordering': ['code', 'pk'],
                'unique_together': {('organisation', 'code')},
            },
        ),
        migrations.AddField(
            model_name='demandepaiement',
            name='compte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demandes_paiement', to='accounts.comptetresorerie'),
        ),
        migrations.CreateModel(
            name='MouvementTresorerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('Entrée', 'Entrée'), ('Sortie', 'Sortie')], max_length=10)),
                ('nature', models.CharField(choices=[('Approvisionnement', 'Approvisionnement'), ('Paiement', 'Paiement')], max_length=20)),
                ('libelle', models.CharField(max_length=255)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=16)),
                ('beneficiaire', models.CharField(blank=True, max_length=255)),
                ('justificatif', models.FileField(blank=True, upload_to='tresorerie/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='accounts.comptetresorerie')),
                ('demande', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvement_tresorerie', to='accounts.demandepaiement')),
                ('executeur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('initiateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_tresorerie', to='accounts.organisation')),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_tresorerie', to='accounts.project')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
