# Generated by Django 6.1 on 2026-10-06 08:50

import django.utils.timezone
from django.db import migrations, models


def remplir_date_embauche_vide(apps, schema_editor):
    # Les salariés existants sans date d'embauche sont comptés à partir d'aujourd'hui.
    User = apps.get_model('accounts', 'User')
    User.objects.filter(date_embauche__isnull=True).update(date_embauche=django.utils.timezone.localdate())


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0070_tresorerie_comptes_mouvements'),
    ]

    operations = [
        migrations.RunPython(remplir_date_embauche_vide, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='date_embauche',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
