# Generated by Django 6.1 on 2026-10-07 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0072_mouvement_origine_demandes_sans_compte'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandepaiement',
            name='motif_refus',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='demandepaiement',
            name='valide_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandepaiement',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='demandepaiement',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('attente', 'En attente de validation'), ('valide', 'Validé — en attente d’exécution'), ('execute', 'Exécuté'), ('refuse', 'Refusé')], default='brouillon', max_length=12),
        ),
    ]
