from django.urls import path

from . import views

urlpatterns = [
    path('organisations/search/', views.OrganisationSearchView.as_view()),
    path('organisations/levels/', views.OrganisationLevelsView.as_view()),
    path('organisations/register/personal/', views.RegisterPersonalOrganisationView.as_view()),
    path('organisations/register/company/', views.RegisterCompanyOrganisationView.as_view()),
    path('organisations/register/member/', views.RegisterMemberView.as_view()),
    path('auth/login/', views.LoginView.as_view()),
    path('employees/', views.EmployeeListView.as_view()),
    path('employees/me/', views.EmployeeMeView.as_view()),
    path('employees/<int:pk>/', views.EmployeeDetailView.as_view()),
    path('employees/<int:pk>/edit/', views.EmployeeAdminEditView.as_view()),
    path('teams/', views.TeamListCreateView.as_view()),
    path('teams/<int:pk>/', views.TeamDetailView.as_view()),
    path('teams/<int:pk>/add-member/', views.TeamAddMemberView.as_view()),
    path('teams/<int:pk>/remove-member/', views.TeamRemoveMemberView.as_view()),
    path('parametres/conges-types/', views.CongeTypeListCreateView.as_view()),
    path('parametres/conges-types/<int:pk>/', views.CongeTypeDetailView.as_view()),
    path('demandes/conges/', views.CongeDemandeListCreateView.as_view()),
    path('demandes/conges/solde/', views.CongeSoldeView.as_view()),
    path('demandes/conges/organisation/', views.OrganisationCongeDemandeListView.as_view()),
    path('demandes/conges/<int:pk>/', views.CongeDemandeDetailView.as_view()),
    path('demandes/conges/<int:pk>/review/', views.CongeDemandeReviewView.as_view()),
    path('demandes/conges/<int:pk>/end/', views.CongeDemandeEndView.as_view()),
    path('demandes/conges-techniques/', views.FermetureTechniqueListCreateView.as_view()),
    path('demandes/conges-techniques/<int:pk>/', views.FermetureTechniqueDetailView.as_view()),
    path('demandes/avances/', views.AvanceDemandeListCreateView.as_view()),
    path('demandes/avances/organisation/', views.OrganisationAvanceDemandeListView.as_view()),
    path('demandes/avances/<int:pk>/', views.AvanceDemandeDetailView.as_view()),
    path('demandes/avances/<int:pk>/review/', views.AvanceDemandeReviewView.as_view()),
    path('architecture-monetaire/lignes/', views.LigneBudgetaireListCreateView.as_view()),
    path('architecture-monetaire/lignes/<int:pk>/', views.LigneBudgetaireDetailView.as_view()),
    path('projects/', views.ProjectListCreateView.as_view()),
    path('projects/<int:pk>/', views.ProjectDetailView.as_view()),
    path('projects/<int:project_id>/lignes/', views.ProjectLigneListCreateView.as_view()),
    path('projects/<int:project_id>/lignes/<int:pk>/', views.ProjectLigneDetailView.as_view()),
    path('task-templates/', views.TaskTemplateListCreateView.as_view()),
    path('task-templates/<int:pk>/', views.TaskTemplateDetailView.as_view()),
    path('tasks/', views.TaskListCreateView.as_view()),
    path('tasks/<int:pk>/', views.TaskDetailView.as_view()),
    path('tasks/<int:pk>/lancer/', views.TaskLaunchView.as_view()),
]
