import { createContext, useContext, useEffect, useState, type ReactNode } from 'react'

export type Language = 'fr' | 'en' | 'pt' | 'es' | 'ar'

const translations: Record<Language, Record<string, string>> = {
  fr: {},
  en: {
    'Accueil':'Home','Pilotage des projets':'Project management','Création de projet':'Create project','Gestion des équipes':'Team management','Trésorerie':'Treasury','Salarié':'Employee','Paramètres':'Settings','Déconnexion':'Log out',
    'Bienvenue dans PERLE, votre système de pilotage intégré.':'Welcome to PERLE, your integrated management system.','Suivez vos projets, leurs indicateurs et leur avancement.':'Track your projects, indicators, and progress.','Créez et planifiez un nouveau projet.':'Create and plan a new project.','Affectez les collaborateurs et suivez les allocations des équipes.':'Assign employees and track team allocations.','Gérez les collaborateurs, les grades et les compétences.':'Manage employees, grades, and skills.','Suivez les paiements, transferts et flux financiers.':'Track payments, transfers, and financial flows.','Consultez et gérez les informations liées aux salariés.':'View and manage employee information.','Gérez les référentiels et les architectures de tâches.':'Manage reference data and task architectures.','Configurez les préférences et les paramètres de PERLE.':'Configure PERLE preferences and settings.','Quittez votre session PERLE en toute sécurité.':'Sign out of PERLE securely.','Équipe de pilotage':'Management team','Modules':'Modules','Accéder':'Open','Pilotage par les EHS':'EHS Management',
    'Vue d’ensemble':'Overview','Mes tâches':'My tasks','Équipe':'Team','Staffing global':'Global staffing','Mes temps':'My time','Historique':'History','Que souhaitez-vous faire ?':'What would you like to do?','Sélectionnez une action pour commencer.':'Select an action to get started.','Nouveau staffing':'New staffing','Exécuter une tâche':'Run a task','Tâches en cours':'Tasks in progress','Tâches terminées':'Completed tasks','En retard':'Overdue','Heures travaillées':'Hours worked','Alertes & notifications':'Alerts & notifications','Mes tâches en cours':'My current tasks','Disponibilité de mon équipe':'My team availability','Historique des tâches':'Task history','Temps total travaillé':'Total time worked','Raccourcis':'Shortcuts','Colonnes':'Columns','Filtres':'Filters','Toutes':'All','En cours':'In progress','En pause':'Paused','À venir':'Upcoming','Terminée':'Completed','Reprendre':'Resume','Mettre en pause':'Pause','Exécution de la tâche':'Task execution','Dernières tâches terminées':'Latest completed tasks','Voir tout':'View all','Voir tout l’historique':'View full history','Gérez votre temps efficacement':'Manage your time efficiently','Informations générales':'General information','Charges et planification':'Costs and planning','Nom du projet':'Project name','Montant HT du projet':'Project amount before tax','Type de montant':'Amount type','Marge':'Margin','Charges transversales':'Overhead costs','Date de début du projet':'Project start date','Date de fin du projet':'Project end date','Récapitulatif automatique':'Automatic summary','Budget d’exécution':'Execution budget','Annuler':'Cancel','Suivant':'Next','Aperçu et récapitulatif du projet':'Project overview and summary','Export Excel':'Export Excel','Modifier le projet':'Edit project','Tableau de bord':'Dashboard','Vue d’ensemble des projets':'Project overview','Projets actifs':'Active projects','Avancement moyen':'Average progress','Budget engagé':'Committed budget','Projets récents':'Recent projects','Voir tous les projets':'View all projects',
    'Consultez rapidement la situation de votre portefeuille de projets.':'Quickly check the status of your project portfolio.','Créer un projet':'Create a project','3 projets prioritaires':'3 priority projects','+6% ce mois-ci':'+6% this month','Dans les objectifs':'On target','Dernière mise à jour aujourd’hui':'Last updated today','À surveiller':'Needs attention','Transformation digitale':'Digital transformation','Optimisation des opérations':'Operations optimization','Déploiement régional':'Regional rollout','Programme qualité':'Quality program',
    'Vue globale de l’ensemble des projets, activités et indicateurs de performance. Consolidez, fonctionnez et réorganisez les lignes.':'Global view of all projects, activities, and performance indicators. Consolidate, run, and reorganize the lines.','Créer de nouveaux projets et consulter leur Projet Plan initial (paramètres financiers, activités, lignes budgétaires...).':'Create new projects and review their initial Project Plan (financial parameters, activities, budget lines...).','Affecter les collaborateurs aux lignes budgétaires, ouvrir les staffings en cours de l’historique des allocations.':'Assign employees to budget lines, view ongoing staffing and allocation history.','Gérer les équipes, collaborateurs, grades et compétences EHS. Suivre l’évolution des équipes et des compétences.':'Manage teams, employees, grades, and EHS skills. Track team and skill development.','Ordonner et suivre les paiements, transferts et flux financiers. Validation, exécution et suivi par la trésorerie.':'Order and track payments, transfers, and financial flows. Validation, execution, and tracking by treasury.','Consulter vos fiches de paie, demander des avances, poser des congés et suivre vos EHS et rémunérations.':'View your pay slips, request advances, apply for leave, and track your EHS and pay.','Gérer les référentiels : architecture des tâches et architecture monétaire (types de dépenses, recettes, transferts...).':'Manage reference data: task architecture and monetary architecture (expense types, revenues, transfers...).',
    'Affecter un collaborateur à une tâche ou un projet.':'Assign an employee to a task or project.','Démarrer, mettre en pause ou reprendre l’exécution d’une tâche.':'Start, pause, or resume the execution of a task.','Période :':'Period:','Cette semaine':'This week','vs semaine dernière':'vs last week','3 collaborateurs libres':'3 available employees','3 membres de votre département sont disponibles pour de nouvelles affectations.':'3 members of your department are available for new assignments.','Voir la liste →':'View the list →','2 tâches en retard':'2 overdue tasks','2 tâches de votre département sont en retard de livraison.':'2 tasks in your department are behind on delivery.','Voir les tâches →':'View the tasks →','5 tâches arrivent à échéance':'5 tasks are due soon','5 tâches arrivent à échéance dans les 3 prochains jours.':'5 tasks are due within the next 3 days.','Nouveau collaborateur':'New employee','Assale Zainabou a rejoint votre département.':'Assale Zainabou has joined your department.','Voir le profil →':'View profile →','Filtrer par collaborateur':'Filter by employee','Tous les collaborateurs':'All employees','Rechercher une tâche...':'Search for a task...','Tâche':'Task','Projet':'Project','Type':'Type','Priorité':'Priority','Assignée par':'Assigned by','Attribuée à':'Assigned to','Matricule':'Employee ID','Début':'Start','Échéance':'Due date','Statut':'Status','Progression':'Progression','Temps':'Time','Action':'Action','Légende :':'Legend:','Tâche EHS':'EHS Task','Tâche Monétaire':'Monetary Task','Afficher':'Show','Le pilotage et la direction ont une visibilité globale sur tous les staffings.':'Management and leadership have full visibility over all staffing.','Seul le pilotage reçoit des alertes sur les collaborateurs non staffés ou en retard sur leurs livrables.':'Only management receives alerts about unstaffed employees or those behind on deliverables.','Voir toute l’équipe →':'View the whole team →','Libres':'Available','Occupés':'Busy','Indisponibles':'Unavailable','Conception UI/UX':'UI/UX Design','Analyse des besoins':'Needs analysis','Spécifications techniques':'Technical specifications','Rapport de staffing':'Staffing report',
    '75% de ma charge':'75% of my workload','Ce mois':'This month','vs mois dernier':'vs last month','Reprise prévue aujourd’hui':'Resuming today','Bravo ! Aucune tâche en retard':'Great! No overdue tasks','Aucun retard':'No delays','Temps travaillé':'Time worked','Filtrer par :':'Filter by:','Manager':'Manager','Tâche Monétaire (consomme de la monnaie)':'Monetary Task (consumes currency)','Tâche EHS (consomme des ressources)':'EHS Task (consumes resources)','Utilisez le chronomètre pour suivre précisément le temps passé sur chaque tâche.':'Use the stopwatch to precisely track the time spent on each task.','Vous pouvez mettre en pause et reprendre à tout moment.':'You can pause and resume at any time.','Suivi en temps réel':'Real-time tracking','Chronométrez vos tâches':'Time your tasks','Pause et reprise':'Pause and resume','Gardez votre progression':'Keep your progress','Historique complet':'Full history','Consultez vos activités':'Review your activity','Rapports personnels':'Personal reports','Analysez votre productivité':'Analyze your productivity','Astuce :':'Tip:','N’oubliez pas de mettre en pause vos tâches lorsque vous êtes interrompu pour des réunions ou d’autres activités.':'Do not forget to pause your tasks when interrupted for meetings or other activities.','Développement du module d’authentification':'Authentication module development','Dernière pause : Aujourd’hui à 10:30':'Last break: Today at 10:30','Durée de la pause : 00:15:20':'Break duration: 00:15:20','Analyse des besoins utilisateurs':'User needs analysis','Rédaction des spécifications':'Drafting specifications','Correction des anomalies':'Bug fixing','Documentation technique':'Technical documentation',
    'Détails du projet':'Project details','Sélection des charges':'Cost selection','Étape 1 : Informations générales du projet':'Step 1: General project information','Renseignez les informations de base de votre projet.':'Enter your project basic information.','Entre 10% et 15%':'Between 10% and 15%','TVA (%)':'VAT (%)','Saisir le taux de TVA si le montant est en TTC':'Enter the VAT rate if the amount is tax-inclusive','La durée totale du projet est de':'The total project duration is','Les résultats sont calculés automatiquement en temps réel.':'Results are calculated automatically in real time.','Reste disponible (après coûts des tâches)':'Remaining available (after task costs)','Coûts des tâches (HT)':'Task costs (before tax)','Total utilisé (HT)':'Total used (before tax)','budget d’exécution':'execution budget','Masquer / Afficher colonnes':'Show / hide columns','Réinitialiser':'Reset','Type de tâche':'Task type','Tous':'All','Sélectionner':'Select','Code':'Code','Nom de la tâche':'Task name','Monétaire':'Monetary','Équivalent EHS':'EHS equivalent','Total':'Total','Nombre de tâches':'Number of tasks','Tâches de type E (EHS)':'Type E tasks (EHS)','Tâches de type D (Monétaire)':'Type D tasks (Monetary)','Total EHS':'Total EHS','Total Monétaire (HT)':'Total Monetary (before tax)','Étude de faisabilité':'Feasibility study','Conception détaillée':'Detailed design','Achat matériel':'Equipment purchase','Développement':'Development','Tests et recette':'Testing and acceptance','Formation utilisateurs':'User training','Mise en production':'Go-live','Conception détaillée de l’application mobile':'Detailed design of the mobile app','Tests et recette utilisateur':'User acceptance testing',
    'Module PERLE':'PERLE Module','Fil d’Ariane':'Breadcrumb',
  },
  pt: {
    'Accueil':'Início','Pilotage des projets':'Gestão de projetos','Création de projet':'Criar projeto','Gestion des équipes':'Gestão de equipes','Trésorerie':'Tesouraria','Salarié':'Funcionário','Paramètres':'Configurações','Déconnexion':'Sair','Équipe de pilotage':'Equipe de gestão','Modules':'Módulos','Accéder':'Acessar',
    'Bienvenue dans PERLE, votre système de pilotage intégré.':'Bem-vindo ao PERLE, seu sistema integrado de gestão.','Suivez vos projets, leurs indicateurs et leur avancement.':'Acompanhe seus projetos, indicadores e progresso.','Créez et planifiez un nouveau projet.':'Crie e planeje um novo projeto.','Affectez les collaborateurs et suivez les allocations des équipes.':'Atribua colaboradores e acompanhe as alocações das equipes.','Gérez les collaborateurs, les grades et les compétences.':'Gerencie colaboradores, níveis e competências.','Suivez les paiements, transferts et flux financiers.':'Acompanhe pagamentos, transferências e fluxos financeiros.','Consultez et gérez les informations liées aux salariés.':'Consulte e gerencie informações dos funcionários.','Gérez les référentiels et les architectures de tâches.':'Gerencie dados de referência e arquiteturas de tarefas.','Configurez les préférences et les paramètres de PERLE.':'Configure as preferências e parâmetros do PERLE.','Quittez votre session PERLE en toute sécurité.':'Saia do PERLE com segurança.',
    'Vue d’ensemble':'Visão geral','Mes tâches':'Minhas tarefas','Équipe':'Equipe','Staffing global':'Alocação global','Mes temps':'Meu tempo','Historique':'Histórico','Que souhaitez-vous faire ?':'O que deseja fazer?','Nouveau staffing':'Nova alocação','Exécuter une tâche':'Executar uma tarefa','Tâches en cours':'Tarefas em andamento','Tâches terminées':'Tarefas concluídas','En retard':'Atrasadas','Heures travaillées':'Horas trabalhadas','Alertes & notifications':'Alertas e notificações','Mes tâches en cours':'Minhas tarefas atuais','Disponibilité de mon équipe':'Disponibilidade da equipe','Historique des tâches':'Histórico de tarefas','Temps total travaillé':'Tempo total trabalhado','Raccourcis':'Atalhos','Colonnes':'Colunas','Filtres':'Filtros','Toutes':'Todas','En cours':'Em andamento','En pause':'Pausada','À venir':'Próxima','Terminée':'Concluída','Reprendre':'Retomar','Mettre en pause':'Pausar','Exécution de la tâche':'Execução da tarefa','Dernières tâches terminées':'Últimas tarefas concluídas','Voir tout':'Ver tudo','Gérez votre temps efficacement':'Gerencie seu tempo com eficiência','Informations générales':'Informações gerais','Charges et planification':'Custos e planejamento','Nom du projet':'Nome do projeto','Montant HT du projet':'Valor do projeto sem impostos','Date de début du projet':'Data de início do projeto','Date de fin du projet':'Data de término do projeto','Récapitulatif automatique':'Resumo automático','Budget d’exécution':'Orçamento de execução','Annuler':'Cancelar','Suivant':'Próximo','Aperçu et récapitulatif du projet':'Visão geral e resumo do projeto','Modifier le projet':'Editar projeto','Tableau de bord':'Painel','Vue d’ensemble des projets':'Visão geral dos projetos','Projets actifs':'Projetos ativos','Avancement moyen':'Progresso médio','Budget engagé':'Orçamento comprometido','Projets récents':'Projetos recentes',
  },
  es: {
    'Accueil':'Inicio','Pilotage des projets':'Gestión de proyectos','Création de projet':'Crear proyecto','Gestion des équipes':'Gestión de equipos','Trésorerie':'Tesorería','Salarié':'Empleado','Paramètres':'Configuración','Déconnexion':'Cerrar sesión','Équipe de pilotage':'Equipo de gestión','Modules':'Módulos','Accéder':'Acceder',
    'Bienvenue dans PERLE, votre système de pilotage intégré.':'Bienvenido a PERLE, su sistema integrado de gestión.','Suivez vos projets, leurs indicateurs et leur avancement.':'Siga sus proyectos, indicadores y progreso.','Créez et planifiez un nouveau projet.':'Cree y planifique un nuevo proyecto.','Affectez les collaborateurs et suivez les allocations des équipes.':'Asigne colaboradores y siga las asignaciones del equipo.','Gérez les collaborateurs, les grades et les compétences.':'Gestione colaboradores, niveles y competencias.','Suivez les paiements, transferts et flux financiers.':'Siga pagos, transferencias y flujos financieros.','Consultez et gérez les informations liées aux salariés.':'Consulte y gestione la información de los empleados.','Gérez les référentiels et les architectures de tâches.':'Gestione datos de referencia y arquitecturas de tareas.','Configurez les préférences et les paramètres de PERLE.':'Configure las preferencias y parámetros de PERLE.','Quittez votre session PERLE en toute sécurité.':'Cierre su sesión de PERLE de forma segura.',
    'Vue d’ensemble':'Vista general','Mes tâches':'Mis tareas','Équipe':'Equipo','Staffing global':'Asignación global','Mes temps':'Mi tiempo','Historique':'Historial','Que souhaitez-vous faire ?':'¿Qué desea hacer?','Nouveau staffing':'Nueva asignación','Exécuter une tâche':'Ejecutar una tarea','Tâches en cours':'Tareas en curso','Tâches terminées':'Tareas terminadas','En retard':'Con retraso','Heures travaillées':'Horas trabajadas','Alertes & notifications':'Alertas y notificaciones','Mes tâches en cours':'Mis tareas actuales','Disponibilité de mon équipe':'Disponibilidad de mi equipo','Historique des tâches':'Historial de tareas','Temps total travaillé':'Tiempo total trabajado','Raccourcis':'Accesos directos','Colonnes':'Columnas','Filtres':'Filtros','Toutes':'Todas','En cours':'En curso','En pause':'En pausa','À venir':'Próxima','Terminée':'Terminada','Reprendre':'Reanudar','Mettre en pause':'Pausar','Exécution de la tâche':'Ejecución de tarea','Dernières tâches terminées':'Últimas tareas terminadas','Voir tout':'Ver todo','Gérez votre temps efficacement':'Gestione su tiempo eficazmente','Informations générales':'Información general','Charges et planification':'Costes y planificación','Nom du projet':'Nombre del proyecto','Montant HT du projet':'Importe del proyecto sin impuestos','Date de début du projet':'Fecha de inicio del proyecto','Date de fin du projet':'Fecha de fin del proyecto','Récapitulatif automatique':'Resumen automático','Budget d’exécution':'Presupuesto de ejecución','Annuler':'Cancelar','Suivant':'Siguiente','Aperçu et récapitulatif du projet':'Vista general y resumen del proyecto','Modifier le projet':'Editar proyecto','Tableau de bord':'Panel','Vue d’ensemble des projets':'Vista general de proyectos','Projets actifs':'Proyectos activos','Avancement moyen':'Progreso medio','Budget engagé':'Presupuesto comprometido','Projets récents':'Proyectos recientes',
  },
  ar: {
    'Accueil':'الرئيسية','Pilotage des projets':'إدارة المشاريع','Création de projet':'إنشاء مشروع','Gestion des équipes':'إدارة الفرق','Trésorerie':'الخزينة','Salarié':'الموظف','Paramètres':'الإعدادات','Déconnexion':'تسجيل الخروج','Équipe de pilotage':'فريق الإدارة','Modules':'الوحدات','Accéder':'فتح',
    'Bienvenue dans PERLE, votre système de pilotage intégré.':'مرحباً بكم في PERLE، نظام الإدارة المتكامل.','Suivez vos projets, leurs indicateurs et leur avancement.':'تابع مشاريعك ومؤشراتها وتقدمها.','Créez et planifiez un nouveau projet.':'أنشئ مشروعاً جديداً وخطط له.','Affectez les collaborateurs et suivez les allocations des équipes.':'عيّن الموظفين وتابع توزيع الفرق.','Gérez les collaborateurs, les grades et les compétences.':'أدر الموظفين والدرجات والمهارات.','Suivez les paiements, transferts et flux financiers.':'تابع المدفوعات والتحويلات والتدفقات المالية.','Consultez et gérez les informations liées aux salariés.':'اعرض معلومات الموظفين وأدرها.','Gérez les référentiels et les architectures de tâches.':'أدر البيانات المرجعية وهياكل المهام.','Configurez les préférences et les paramètres de PERLE.':'اضبط تفضيلات وإعدادات PERLE.','Quittez votre session PERLE en toute sécurité.':'سجّل الخروج من PERLE بأمان.',
    'Vue d’ensemble':'نظرة عامة','Mes tâches':'مهامي','Équipe':'الفريق','Staffing global':'التوظيف العام','Mes temps':'وقتي','Historique':'السجل','Que souhaitez-vous faire ?':'ماذا تريد أن تفعل؟','Nouveau staffing':'توظيف جديد','Exécuter une tâche':'تنفيذ مهمة','Tâches en cours':'المهام الجارية','Tâches terminées':'المهام المكتملة','En retard':'متأخرة','Heures travaillées':'ساعات العمل','Alertes & notifications':'التنبيهات والإشعارات','Mes tâches en cours':'مهامي الحالية','Disponibilité de mon équipe':'توفر فريقي','Historique des tâches':'سجل المهام','Temps total travaillé':'إجمالي وقت العمل','Raccourcis':'اختصارات','Colonnes':'الأعمدة','Filtres':'التصفية','Toutes':'الكل','En cours':'قيد التنفيذ','En pause':'متوقفة','À venir':'قادمة','Terminée':'مكتملة','Reprendre':'استئناف','Mettre en pause':'إيقاف مؤقت','Exécution de la tâche':'تنفيذ المهمة','Dernières tâches terminées':'آخر المهام المكتملة','Voir tout':'عرض الكل','Gérez votre temps efficacement':'أدر وقتك بكفاءة','Informations générales':'معلومات عامة','Charges et planification':'التكاليف والتخطيط','Nom du projet':'اسم المشروع','Montant HT du projet':'قيمة المشروع قبل الضريبة','Date de début du projet':'تاريخ بدء المشروع','Date de fin du projet':'تاريخ انتهاء المشروع','Récapitulatif automatique':'ملخص تلقائي','Budget d’exécution':'ميزانية التنفيذ','Annuler':'إلغاء','Suivant':'التالي','Aperçu et récapitulatif du projet':'نظرة عامة وملخص المشروع','Modifier le projet':'تعديل المشروع','Tableau de bord':'لوحة التحكم','Vue d’ensemble des projets':'نظرة عامة على المشاريع','Projets actifs':'المشاريع النشطة','Avancement moyen':'متوسط التقدم','Budget engagé':'الميزانية الملتزم بها','Projets récents':'المشاريع الأخيرة',
  },
}

const I18nContext = createContext({ language: 'fr' as Language, setLanguage: (language: Language) => { void language }, t: (text: string) => text })
Object.assign(translations.en, {
  'Équipe Pilotage':'Management Team','Vue globale de l’ensemble des projets, activités et indicateurs de performance. Consolidez, fonctionnez et réorganisez les lignes.':'Global view of all projects, activities, and performance indicators. Consolidate and reorganize project lines.','Créer de nouveaux projets et consulter leur Projet Plan initial (paramètres financiers, activités, lignes budgétaires...).':'Create new projects and view their initial Project Plan (financial settings, activities, budget lines, etc.).','Affecter les collaborateurs aux lignes budgétaires, ouvrir les staffings en cours de l’historique des allocations.':'Assign employees to budget lines and review current and historical staffing allocations.','Gérer les équipes, collaborateurs, grades et compétences EHS. Suivre l’évolution des équipes et des compétences.':'Manage teams, employees, grades, and EHS skills. Track team and skill development.','Ordonner et suivre les paiements, transferts et flux financiers. Validation, exécution et suivi par la trésorerie.':'Order and track payments, transfers, and financial flows. Treasury validation, execution, and monitoring.','Consulter vos fiches de paie, demander des avances, poser des congés et suivre vos EHS et rémunérations.':'View payslips, request advances and leave, and track EHS and compensation.','Gérer les référentiels : architecture des tâches et architecture monétaire (types de dépenses, recettes, transferts...).':'Manage reference data: task and monetary architecture (expenses, revenue, transfers, etc.).',
  'Détails du projet':'Project details','Sélection des charges':'Cost selection','Étape 1 : Informations générales du projet':'Step 1: General project information','Renseignez les informations de base de votre projet.':'Enter the project’s basic information.','Projet d’étude et de mise en œuvre du système ERP':'ERP system study and implementation project','Type de montant':'Amount type','Marge (%)':'Margin (%)','Charges transversales (%)':'Overhead costs (%)','TVA (%)':'VAT (%)','Entre 10% et 15%':'Between 10% and 15%','Saisir le taux de TVA si le montant est en TTC':'Enter the VAT rate if the amount includes tax','Montant HT':'Amount before tax','Marge (40%)':'Margin (40%)','Charges transversales (12%)':'Overhead costs (12%)','La durée totale du projet est de':'The total project duration is','245 jours.':'245 days.','Les résultats sont calculés automatiquement en temps réel.':'Results are calculated automatically in real time.','Reste disponible (après coûts des tâches)':'Remaining amount (after task costs)','24,22% du budget d’exécution':'24.22% of execution budget','Coûts des tâches (HT)':'Task costs (before tax)','Total utilisé (HT)':'Total used (before tax)','75,78% du budget d’exécution':'75.78% of execution budget','Masquer / Afficher colonnes':'Hide / Show columns','Réinitialiser':'Reset','Type de tâche':'Task type','Tous':'All','Nom de la tâche':'Task name','Monétaire (FCFA)':'Monetary (FCFA)','Équivalent EHS':'EHS equivalent','Assignée par':'Assigned by','Attribuée à':'Assigned to','Début':'Start','Fin':'End','Sélectionner⌄':'Select⌄','Nombre de tâches':'Number of tasks','Tâches de type E (EHS)':'Type E tasks (EHS)','Tâches de type D (Monétaire)':'Type D tasks (Monetary)','Total Monétaire (HT)':'Total monetary (before tax)','Étude de faisabilité':'Feasibility study','Conception détaillée':'Detailed design','Achat matériel':'Equipment purchase','Développement':'Development','Tests et recette':'Testing and acceptance','Formation utilisateurs':'User training','Mise en production':'Go-live',
  'Consultez rapidement la situation de votre portefeuille de projets.':'Quickly review your project portfolio status.','Créer un projet':'Create project','3 projets prioritaires':'3 priority projects','+6% ce mois-ci':'+6% this month','Dans les objectifs':'On target','Transformation digitale':'Digital transformation','Optimisation des opérations':'Operations optimization','Déploiement régional':'Regional rollout','Programme qualité':'Quality program','À surveiller':'Needs attention','Dernière mise à jour aujourd’hui':'Last updated today',
  'Affecter un collaborateur à une tâche ou un projet.':'Assign an employee to a task or project.','Démarrer, mettre en pause ou reprendre l’exécution d’une tâche.':'Start, pause, or resume a task.','Période :':'Period:','Cette semaine':'This week','vs semaine dernière':'vs last week','3 collaborateurs libres':'3 available employees','3 membres de votre département sont disponibles pour de nouvelles affectations.':'3 members of your department are available for new assignments.','Voir la liste →':'View list →','2 tâches en retard':'2 overdue tasks','2 tâches de votre département sont en retard de livraison.':'2 tasks in your department are overdue.','Voir les tâches →':'View tasks →','5 tâches arrivent à échéance':'5 tasks are approaching their deadline','5 tâches arrivent à échéance dans les 3 prochains jours.':'5 tasks are due within the next 3 days.','Nouveau collaborateur':'New employee','Assale Zainabou a rejoint votre département.':'Assale Zainabou joined your department.','Voir le profil →':'View profile →','Filtrer par collaborateur':'Filter by employee','Tous les collaborateurs':'All employees','Rechercher une tâche...':'Search for a task...','Tâche':'Task','Projet':'Project','Priorité':'Priority','Matricule':'Employee ID','Échéance':'Deadline','Statut':'Status','Progression':'Progress','Temps':'Time','Action':'Action','Légende :':'Legend:','Tâche EHS':'EHS task','Tâche Monétaire':'Monetary task','Afficher':'Show','Le pilotage et la direction ont une visibilité globale sur tous les staffings.':'Management has full visibility across all staffing assignments.','Seul le pilotage reçoit des alertes sur les collaborateurs non staffés ou en retard sur leurs livrables.':'Only management receives alerts about unassigned employees or overdue deliverables.','Voir toute l’équipe →':'View full team →','3 libres sur 10':'3 available out of 10','Libres (3)':'Available (3)','Occupés (6)':'Busy (6)','Indisponibles (1)':'Unavailable (1)','Rapport de staffing':'Staffing report','Lun':'Mon','Mar':'Tue','Mer':'Wed','Jeu':'Thu','Ven':'Fri','Sam':'Sat','Dim':'Sun',
  '75% de ma charge':'75% of my workload','Ce mois':'This month','vs mois dernier':'vs last month','Reprise prévue aujourd’hui':'Resume scheduled today','Bravo ! Aucune tâche en retard':'Great! No overdue tasks','Aucun retard':'No delays','Temps travaillé':'Time worked','Filtrer par :':'Filter by:','Affichage 1 - 3 sur 3 tâches':'Showing 1–3 of 3 tasks','Tâche EHS (consomme des ressources)':'EHS task (uses resources)','Tâche Monétaire (consomme de la monnaie)':'Monetary task (uses money)','Utilisez le chronomètre pour suivre précisément le temps passé sur chaque tâche.':'Use the timer to accurately track time spent on each task.','Vous pouvez mettre en pause et reprendre à tout moment.':'You can pause and resume at any time.','Suivi en temps réel':'Real-time tracking','Chronométrez vos tâches':'Time your tasks','Pause et reprise':'Pause and resume','Gardez votre progression':'Keep your progress','Historique complet':'Complete history','Consultez vos activités':'View your activities','Rapports personnels':'Personal reports','Analysez votre productivité':'Analyze your productivity','Astuce :':'Tip:','N’oubliez pas de mettre en pause vos tâches lorsque vous êtes interrompu pour des réunions ou d’autres activités.':'Remember to pause tasks when interrupted by meetings or other activities.','Développement du module d’authentification':'Authentication module development','Temps total travaillé':'Total time worked','Dernière pause : Aujourd’hui à 10:30':'Last pause: Today at 10:30','Durée de la pause : 00:15:20':'Pause duration: 00:15:20','Analyse des besoins utilisateurs':'User needs analysis','Rédaction des spécifications':'Specification writing','Correction des anomalies':'Bug fixes','Documentation technique':'Technical documentation','Conception UI/UX':'UI/UX design','Analyse des besoins':'Needs analysis','Spécifications techniques':'Technical specifications','Haute':'High','Moyenne':'Medium','Basse':'Low',
})
Object.assign(translations.pt, {
  'Équipe Pilotage':'Equipe de gestão','Détails du projet':'Detalhes do projeto','Sélection des charges':'Seleção de custos','Étape 1 : Informations générales du projet':'Etapa 1: Informações gerais do projeto','Renseignez les informations de base de votre projet.':'Insira as informações básicas do projeto.','Projet d’étude et de mise en œuvre du système ERP':'Projeto de estudo e implementação do sistema ERP','Type de montant':'Tipo de valor','Marge (%)':'Margem (%)','Charges transversales (%)':'Custos indiretos (%)','TVA (%)':'IVA (%)','Entre 10% et 15%':'Entre 10% e 15%','Saisir le taux de TVA si le montant est en TTC':'Insira a taxa de IVA se o valor incluir impostos','Montant HT':'Valor sem impostos','Marge (40%)':'Margem (40%)','Charges transversales (12%)':'Custos indiretos (12%)','La durée totale du projet est de':'A duração total do projeto é','245 jours.':'245 dias.','Les résultats sont calculés automatiquement en temps réel.':'Os resultados são calculados automaticamente em tempo real.','Reste disponible (après coûts des tâches)':'Restante disponível (após custos das tarefas)','Coûts des tâches (HT)':'Custos das tarefas (sem impostos)','Total utilisé (HT)':'Total utilizado (sem impostos)','Masquer / Afficher colonnes':'Ocultar / Mostrar colunas','Réinitialiser':'Redefinir','Type de tâche':'Tipo de tarefa','Tous':'Todos','Nom de la tâche':'Nome da tarefa','Monétaire (FCFA)':'Monetário (FCFA)','Équivalent EHS':'Equivalente EHS','Assignée par':'Atribuída por','Attribuée à':'Atribuída a','Début':'Início','Fin':'Fim','Sélectionner⌄':'Selecionar⌄','Nombre de tâches':'Número de tarefas','Tâches de type E (EHS)':'Tarefas tipo E (EHS)','Tâches de type D (Monétaire)':'Tarefas tipo D (Monetárias)','Total Monétaire (HT)':'Total monetário (sem impostos)','Étude de faisabilité':'Estudo de viabilidade','Conception détaillée':'Projeto detalhado','Achat matériel':'Compra de equipamentos','Développement':'Desenvolvimento','Tests et recette':'Testes e aceitação','Formation utilisateurs':'Treinamento de usuários','Mise en production':'Entrada em produção','Consultez rapidement la situation de votre portefeuille de projets.':'Consulte rapidamente a situação do seu portfólio de projetos.','Créer un projet':'Criar projeto','3 projets prioritaires':'3 projetos prioritários','Dans les objectifs':'Dentro das metas','Projets récents':'Projetos recentes','Voir tous les projets':'Ver todos os projetos','À surveiller':'Requer atenção','Dernière mise à jour aujourd’hui':'Última atualização hoje',
  'Affecter un collaborateur à une tâche ou un projet.':'Atribuir um colaborador a uma tarefa ou projeto.','Démarrer, mettre en pause ou reprendre l’exécution d’une tâche.':'Iniciar, pausar ou retomar uma tarefa.','Période :':'Período:','Cette semaine':'Esta semana','vs semaine dernière':'vs semana passada','3 collaborateurs libres':'3 colaboradores disponíveis','Voir la liste →':'Ver lista →','2 tâches en retard':'2 tarefas atrasadas','Voir les tâches →':'Ver tarefas →','5 tâches arrivent à échéance':'5 tarefas próximas do prazo','Nouveau collaborateur':'Novo colaborador','Voir le profil →':'Ver perfil →','Filtrer par collaborateur':'Filtrar por colaborador','Tous les collaborateurs':'Todos os colaboradores','Rechercher une tâche...':'Pesquisar uma tarefa...','Tâche':'Tarefa','Projet':'Projeto','Priorité':'Prioridade','Matricule':'Matrícula','Échéance':'Prazo','Statut':'Status','Progression':'Progresso','Temps':'Tempo','Action':'Ação','Légende :':'Legenda:','Afficher':'Exibir','Voir toute l’équipe →':'Ver toda a equipe →','Libres (3)':'Disponíveis (3)','Occupés (6)':'Ocupados (6)','Indisponibles (1)':'Indisponíveis (1)','Rapport de staffing':'Relatório de alocação','75% de ma charge':'75% da minha carga','Ce mois':'Este mês','vs mois dernier':'vs mês passado','Reprise prévue aujourd’hui':'Retomada prevista hoje','Bravo ! Aucune tâche en retard':'Ótimo! Nenhuma tarefa atrasada','Aucun retard':'Sem atrasos','Temps travaillé':'Tempo trabalhado','Filtrer par :':'Filtrar por:','Utilisez le chronomètre pour suivre précisément le temps passé sur chaque tâche.':'Use o cronômetro para acompanhar o tempo gasto em cada tarefa.','Vous pouvez mettre en pause et reprendre à tout moment.':'Você pode pausar e retomar a qualquer momento.','Suivi en temps réel':'Acompanhamento em tempo real','Pause et reprise':'Pausa e retomada','Historique complet':'Histórico completo','Rapports personnels':'Relatórios pessoais','Astuce :':'Dica:','Développement du module d’authentification':'Desenvolvimento do módulo de autenticação','Dernière pause : Aujourd’hui à 10:30':'Última pausa: Hoje às 10:30','Durée de la pause : 00:15:20':'Duração da pausa: 00:15:20','Haute':'Alta','Moyenne':'Média','Basse':'Baixa',
})
Object.assign(translations.es, {
  'Équipe Pilotage':'Equipo de gestión','Détails du projet':'Detalles del proyecto','Sélection des charges':'Selección de costes','Étape 1 : Informations générales du projet':'Paso 1: Información general del proyecto','Renseignez les informations de base de votre projet.':'Introduzca la información básica del proyecto.','Projet d’étude et de mise en œuvre du système ERP':'Proyecto de estudio e implementación del sistema ERP','Type de montant':'Tipo de importe','Marge (%)':'Margen (%)','Charges transversales (%)':'Costes indirectos (%)','TVA (%)':'IVA (%)','Entre 10% et 15%':'Entre 10% y 15%','Saisir le taux de TVA si le montant est en TTC':'Introduzca el IVA si el importe incluye impuestos','Montant HT':'Importe sin impuestos','Marge (40%)':'Margen (40%)','Charges transversales (12%)':'Costes indirectos (12%)','La durée totale du projet est de':'La duración total del proyecto es','245 jours.':'245 días.','Les résultats sont calculés automatiquement en temps réel.':'Los resultados se calculan automáticamente en tiempo real.','Reste disponible (après coûts des tâches)':'Disponible restante (después de costes)','Coûts des tâches (HT)':'Costes de tareas (sin impuestos)','Total utilisé (HT)':'Total utilizado (sin impuestos)','Masquer / Afficher colonnes':'Ocultar / Mostrar columnas','Réinitialiser':'Restablecer','Type de tâche':'Tipo de tarea','Tous':'Todos','Nom de la tâche':'Nombre de tarea','Monétaire (FCFA)':'Monetario (FCFA)','Équivalent EHS':'Equivalente EHS','Assignée par':'Asignada por','Attribuée à':'Asignada a','Début':'Inicio','Fin':'Fin','Sélectionner⌄':'Seleccionar⌄','Nombre de tâches':'Número de tareas','Tâches de type E (EHS)':'Tareas tipo E (EHS)','Tâches de type D (Monétaire)':'Tareas tipo D (Monetarias)','Total Monétaire (HT)':'Total monetario (sin impuestos)','Étude de faisabilité':'Estudio de viabilidad','Conception détaillée':'Diseño detallado','Achat matériel':'Compra de equipos','Développement':'Desarrollo','Tests et recette':'Pruebas y aceptación','Formation utilisateurs':'Formación de usuarios','Mise en production':'Puesta en producción','Consultez rapidement la situation de votre portefeuille de projets.':'Consulte rápidamente el estado de su cartera de proyectos.','Créer un projet':'Crear proyecto','3 projets prioritaires':'3 proyectos prioritarios','Dans les objectifs':'Dentro de los objetivos','Projets récents':'Proyectos recientes','Voir tous les projets':'Ver todos los proyectos','À surveiller':'Requiere atención','Dernière mise à jour aujourd’hui':'Última actualización hoy',
  'Affecter un collaborateur à une tâche ou un projet.':'Asignar un colaborador a una tarea o proyecto.','Démarrer, mettre en pause ou reprendre l’exécution d’une tâche.':'Iniciar, pausar o reanudar una tarea.','Période :':'Período:','Cette semaine':'Esta semana','vs semaine dernière':'vs semana pasada','3 collaborateurs libres':'3 colaboradores disponibles','Voir la liste →':'Ver lista →','2 tâches en retard':'2 tareas atrasadas','Voir les tâches →':'Ver tareas →','5 tâches arrivent à échéance':'5 tareas próximas al plazo','Nouveau collaborateur':'Nuevo colaborador','Voir le profil →':'Ver perfil →','Filtrer par collaborateur':'Filtrar por colaborador','Tous les collaborateurs':'Todos los colaboradores','Rechercher une tâche...':'Buscar una tarea...','Tâche':'Tarea','Projet':'Proyecto','Priorité':'Prioridad','Matricule':'Matrícula','Échéance':'Fecha límite','Statut':'Estado','Progression':'Progreso','Temps':'Tiempo','Action':'Acción','Légende :':'Leyenda:','Afficher':'Mostrar','Voir toute l’équipe →':'Ver todo el equipo →','Libres (3)':'Disponibles (3)','Occupés (6)':'Ocupados (6)','Indisponibles (1)':'No disponibles (1)','Rapport de staffing':'Informe de asignación','75% de ma charge':'75% de mi carga','Ce mois':'Este mes','vs mois dernier':'vs mes pasado','Reprise prévue aujourd’hui':'Reanudación prevista hoy','Bravo ! Aucune tâche en retard':'¡Excelente! No hay tareas atrasadas','Aucun retard':'Sin retrasos','Temps travaillé':'Tiempo trabajado','Filtrer par :':'Filtrar por:','Utilisez le chronomètre pour suivre précisément le temps passé sur chaque tâche.':'Use el cronómetro para controlar el tiempo dedicado a cada tarea.','Vous pouvez mettre en pause et reprendre à tout moment.':'Puede pausar y reanudar en cualquier momento.','Suivi en temps réel':'Seguimiento en tiempo real','Pause et reprise':'Pausa y reanudación','Historique complet':'Historial completo','Rapports personnels':'Informes personales','Astuce :':'Consejo:','Développement du module d’authentification':'Desarrollo del módulo de autenticación','Dernière pause : Aujourd’hui à 10:30':'Última pausa: Hoy a las 10:30','Durée de la pause : 00:15:20':'Duración de la pausa: 00:15:20','Haute':'Alta','Moyenne':'Media','Basse':'Baja',
})
Object.assign(translations.ar, {
  'Équipe Pilotage':'فريق الإدارة','Détails du projet':'تفاصيل المشروع','Sélection des charges':'اختيار التكاليف','Étape 1 : Informations générales du projet':'الخطوة 1: معلومات المشروع العامة','Renseignez les informations de base de votre projet.':'أدخل المعلومات الأساسية للمشروع.','Projet d’étude et de mise en œuvre du système ERP':'مشروع دراسة وتنفيذ نظام ERP','Type de montant':'نوع المبلغ','Marge (%)':'الهامش (%)','Charges transversales (%)':'التكاليف غير المباشرة (%)','TVA (%)':'ضريبة القيمة المضافة (%)','Entre 10% et 15%':'بين 10% و15%','Saisir le taux de TVA si le montant est en TTC':'أدخل نسبة الضريبة إذا كان المبلغ شاملاً للضريبة','Montant HT':'المبلغ قبل الضريبة','Marge (40%)':'الهامش (40%)','Charges transversales (12%)':'التكاليف غير المباشرة (12%)','La durée totale du projet est de':'المدة الإجمالية للمشروع هي','245 jours.':'245 يوماً.','Les résultats sont calculés automatiquement en temps réel.':'تُحسب النتائج تلقائياً في الوقت الفعلي.','Reste disponible (après coûts des tâches)':'المتبقي المتاح بعد تكاليف المهام','Coûts des tâches (HT)':'تكاليف المهام قبل الضريبة','Total utilisé (HT)':'الإجمالي المستخدم قبل الضريبة','Masquer / Afficher colonnes':'إخفاء / إظهار الأعمدة','Réinitialiser':'إعادة تعيين','Type de tâche':'نوع المهمة','Tous':'الكل','Nom de la tâche':'اسم المهمة','Monétaire (FCFA)':'نقدي (FCFA)','Équivalent EHS':'ما يعادل EHS','Assignée par':'عيّنها','Attribuée à':'مُسندة إلى','Début':'البداية','Fin':'النهاية','Sélectionner⌄':'اختيار⌄','Nombre de tâches':'عدد المهام','Tâches de type E (EHS)':'مهام النوع E (EHS)','Tâches de type D (Monétaire)':'مهام النوع D (نقدية)','Total Monétaire (HT)':'الإجمالي النقدي قبل الضريبة','Étude de faisabilité':'دراسة الجدوى','Conception détaillée':'التصميم التفصيلي','Achat matériel':'شراء المعدات','Développement':'التطوير','Tests et recette':'الاختبار والقبول','Formation utilisateurs':'تدريب المستخدمين','Mise en production':'بدء التشغيل','Consultez rapidement la situation de votre portefeuille de projets.':'راجع حالة محفظة مشاريعك بسرعة.','Créer un projet':'إنشاء مشروع','3 projets prioritaires':'3 مشاريع ذات أولوية','Dans les objectifs':'ضمن الأهداف','Projets récents':'المشاريع الأخيرة','Voir tous les projets':'عرض كل المشاريع','À surveiller':'يتطلب الانتباه','Dernière mise à jour aujourd’hui':'آخر تحديث اليوم',
  'Affecter un collaborateur à une tâche ou un projet.':'عيّن موظفاً لمهمة أو مشروع.','Démarrer, mettre en pause ou reprendre l’exécution d’une tâche.':'ابدأ المهمة أو أوقفها مؤقتاً أو استأنفها.','Période :':'الفترة:','Cette semaine':'هذا الأسبوع','vs semaine dernière':'مقارنة بالأسبوع الماضي','3 collaborateurs libres':'3 موظفين متاحين','Voir la liste →':'عرض القائمة ←','2 tâches en retard':'مهمتان متأخرتان','Voir les tâches →':'عرض المهام ←','5 tâches arrivent à échéance':'5 مهام تقترب من موعدها','Nouveau collaborateur':'موظف جديد','Voir le profil →':'عرض الملف ←','Filtrer par collaborateur':'تصفية حسب الموظف','Tous les collaborateurs':'كل الموظفين','Rechercher une tâche...':'البحث عن مهمة...','Tâche':'المهمة','Projet':'المشروع','Priorité':'الأولوية','Matricule':'الرقم الوظيفي','Échéance':'الموعد النهائي','Statut':'الحالة','Progression':'التقدم','Temps':'الوقت','Action':'الإجراء','Légende :':'المفتاح:','Afficher':'عرض','Voir toute l’équipe →':'عرض الفريق بالكامل ←','Libres (3)':'متاحون (3)','Occupés (6)':'مشغولون (6)','Indisponibles (1)':'غير متاح (1)','Rapport de staffing':'تقرير التوظيف','75% de ma charge':'75% من عبء عملي','Ce mois':'هذا الشهر','vs mois dernier':'مقارنة بالشهر الماضي','Reprise prévue aujourd’hui':'الاستئناف مقرر اليوم','Bravo ! Aucune tâche en retard':'رائع! لا توجد مهام متأخرة','Aucun retard':'لا تأخير','Temps travaillé':'وقت العمل','Filtrer par :':'تصفية حسب:','Utilisez le chronomètre pour suivre précisément le temps passé sur chaque tâche.':'استخدم المؤقت لتتبع الوقت المستغرق في كل مهمة بدقة.','Vous pouvez mettre en pause et reprendre à tout moment.':'يمكنك الإيقاف المؤقت والاستئناف في أي وقت.','Suivi en temps réel':'تتبع في الوقت الفعلي','Pause et reprise':'إيقاف واستئناف','Historique complet':'سجل كامل','Rapports personnels':'تقارير شخصية','Astuce :':'نصيحة:','Développement du module d’authentification':'تطوير وحدة المصادقة','Dernière pause : Aujourd’hui à 10:30':'آخر توقف: اليوم الساعة 10:30','Durée de la pause : 00:15:20':'مدة التوقف: 00:15:20','Haute':'عالية','Moyenne':'متوسطة','Basse':'منخفضة',
})
// Tableau de bord administrateur
Object.assign(translations.en, {
  'Administration':'Administration','Tableau de bord administrateur':'Administrator dashboard','Supervision de l’activité, de la sécurité et de la santé du système':'Monitoring of activity, security, and system health','Supervision de l’activité, de la sécurité et de la santé du système.':'Monitoring of activity, security, and system health.','Utilisateurs':'Users','Rôles et permissions':'Roles and permissions','Référentiels':'Reference data','Paramètres globaux':'Global settings','Import / Export':'Import / Export','Journal d’audit':'Audit log','Sauvegardes et maintenance':'Backups and maintenance','Retour à PERLE':'Back to PERLE','← Retour au tableau de bord':'← Back to the dashboard',
  'Indicateurs clés':'Key indicators','Utilisateurs actifs':'Active users','Sessions en cours':'Open sessions','Erreurs (24 h)':'Errors (24 h)','Dernière sauvegarde':'Last backup','Tâches Celery':'Celery tasks','État global du système':'Overall system status','Opérationnel':'Operational','Dégradé':'Degraded','Critique':'Critical','Ouvrir le détail →':'Open details →',
  'Graphiques de supervision':'Monitoring charts','Activité et connexions':'Activity and sign-ins','Évolution des erreurs':'Error trend','Utilisation du stockage':'Storage usage','Santé des tâches Celery':'Celery task health','État des sauvegardes':'Backup status','Répartition des utilisateurs':'User breakdown','Actions administratives et audit':'Administrative actions and audit','Par rôle':'By role','Par statut':'By status','Ventilation par catégorie':'Breakdown by category','Espace utilisé':'Used space','Espace disponible':'Available space','Capacité totale':'Total capacity','Évolution':'Change','Taux de réussite':'Success rate','Durée moyenne':'Average duration','Tâche la plus longue':'Longest task','Tâches bloquées':'Blocked tasks',
  'Sécurité et supervision opérationnelle':'Security and operational monitoring','Connexions récentes':'Recent sign-ins','Voir toutes les connexions':'View all sign-ins','Alertes système':'System alerts','Voir toutes les alertes':'View all alerts','Toutes':'All','Élevé':'High','Moyen':'Medium','Information':'Information','Ouvrir':'Open','Prendre en charge':'Take ownership','Marquer résolue':'Mark as resolved','Ignorer':'Dismiss','Voir le journal':'View the log','Voir détail':'View details','Réussie':'Successful','Échouée':'Failed','Nouvelle':'New','Prise en charge':'In progress','Résolue':'Resolved','Ignorée':'Dismissed',
  'Actions rapides':'Quick actions','Lancer une sauvegarde manuelle':'Run a manual backup','Purger le cache':'Purge the cache','Voir le journal d’audit':'View the audit log','Nouvelle notification broadcast':'New broadcast notification','Ajouter un utilisateur':'Add a user','Consulter les erreurs':'Review the errors','Tester une restauration':'Test a restore','Journal d’audit récent':'Recent audit log','Voir le journal d’audit complet':'View the full audit log','10 derniers événements administratifs':'Last 10 administrative events',
  'Actualiser':'Refresh','⎙ Exporter en PDF':'⎙ Export as PDF','Export CSV':'Export CSV','Aujourd’hui':'Today','7 derniers jours':'Last 7 days','30 derniers jours':'Last 30 days','Période personnalisée':'Custom period','Actualisation automatique':'Automatic refresh','Arrêtée':'Off','30 secondes':'30 seconds','1 minute':'1 minute','5 minutes':'5 minutes','États des widgets (démo)':'Widget states (demo)','Données disponibles':'Data available','Chargement':'Loading','Aucune donnée':'No data','Erreur de chargement':'Loading error','Réessayer':'Retry','Chargement des données…':'Loading data…','Erreur de chargement des données.':'Failed to load data.','Afficher le tableau de données':'Show the data table','Masquer le tableau de données':'Hide the data table',
  'Mon profil':'My profile','Préférences':'Preferences','Sécurité et MFA':'Security and MFA','Annuler':'Cancel','Conséquences':'Consequences','Action demandée':'Requested action','Exécutée par':'Performed by','Valeur avant modification':'Value before change','Valeur après modification':'Value after change','Auteur':'Author','Date':'Date','Adresse IP':'IP address','Contexte ou motif':'Context or reason','Sensibilité':'Sensitivity','Identifiant de corrélation':'Correlation ID','Élevée':'High','Moyenne':'Medium','Faible':'Low',
})

// Tableau de bord de direction (accueil du workspace directeur)
Object.assign(translations.en, {
  'Direction':'Management','Tableau de bord de direction':'Management dashboard','Pilotage financier, portefeuille de projets, ressources et trésorerie de l’entreprise.':'Financial steering, project portfolio, resources, and company treasury.','Mois en cours':'Current month','Trimestre en cours':'Current quarter','Exercice 2026':'FY 2026',
  'Chiffre d’affaires':'Revenue','Marge nette':'Net margin','Taux d’occupation':'Utilization rate','Trésorerie disponible':'Available cash','Tâches en retard':'Overdue tasks','Objectif annuel : 20 %':'Annual target: 20%','Seuil de confort : 80 M FCFA':'Comfort threshold: 80M FCFA','Réparties sur 2 projets':'Spread across 2 projects','2 livraisons prévues ce mois':'2 deliveries planned this month','10 collaborateurs disponibles':'10 employees available',
  'Performance financière':'Financial performance','Répartition du budget':'Budget breakdown','Portefeuille de projets':'Project portfolio','Consommation EHS':'EHS consumption','Charge des équipes':'Team workload','Livrables et échéances':'Deliverables and deadlines','Alertes de direction':'Management alerts','Projets prioritaires':'Priority projects',
  'Par nature':'By nature','Par département':'By department','Recettes':'Revenue','Dépenses':'Costs','Taux de marge (%)':'Margin rate (%)','Solde de trésorerie':'Cash balance','Flux net positif':'Positive net flow','Flux net négatif':'Negative net flow','Avancement':'Progress','Budget consommé':'Budget used','Staffés':'Assigned','Disponibles':'Available','Indisponibles':'Unavailable','Livrés':'Delivered','En retard':'Overdue','Sous contrôle':'Under control','À surveiller':'Needs attention','Dépassement':'Overrun',
  'EHS consommés':'EHS consumed','EHS planifiés':'EHS planned','Reste disponible':'Remaining','Consommation par département':'Consumption by department','Voir tous les projets':'View all projects','Ouvrir la trésorerie':'Open treasury','Ouvrir le staffing':'Open staffing','Ouvrir le pilotage des projets':'Open project management','Ouvrir le module concerné →':'Open the related module →','Responsable':'Owner','Échéance':'Deadline','Marge':'Margin','Projet':'Project',
})

const originalText = new WeakMap<Text, string>()
/** Dernière valeur écrite par le traducteur : permet de détecter les réécritures de React. */
const appliedText = new WeakMap<Text, string>()
const originalAttributes = new WeakMap<Element, Record<string, string>>()
const translatableFrenchText = new Set(Object.keys(translations.en))

export function I18nProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => (localStorage.getItem('perle-language') as Language) || 'fr')
  useEffect(() => {
    localStorage.setItem('perle-language', language)
    document.documentElement.lang = language
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr'

    const translateTree = (root: Node) => {
      const translateTextNode = (node: Text) => {
        const parent = node.parentElement
        if (!parent || ['SCRIPT', 'STYLE'].includes(parent.tagName)) return
        // Si React a réécrit le nœud depuis notre dernière traduction, la valeur
        // d'origine mémorisée est périmée : on repart du nouveau contenu.
        if (!originalText.has(node) || appliedText.get(node) !== node.nodeValue) {
          if (!translatableFrenchText.has((node.nodeValue ?? '').trim())) {
            originalText.delete(node)
            return
          }
          originalText.set(node, node.nodeValue ?? '')
        }
        const original = originalText.get(node) ?? ''
        const key = original.trim()
        const translated = translations[language][key] ?? (language === 'fr' ? key : translations.en[key]) ?? key
        const nextValue = key ? original.replace(key, translated) : original
        if (node.nodeValue !== nextValue) node.nodeValue = nextValue
        appliedText.set(node, nextValue)
      }

      if (root.nodeType === Node.TEXT_NODE) translateTextNode(root as Text)
      const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT)
      let node = walker.nextNode() as Text | null
      while (node) {
        translateTextNode(node)
        node = walker.nextNode() as Text | null
      }

      if (root instanceof Element) {
        const elements = [root, ...root.querySelectorAll('*')]
        elements.forEach((element) => {
          if (!originalAttributes.has(element)) {
            originalAttributes.set(element, Object.fromEntries(['placeholder', 'title', 'aria-label'].map((name) => {
              const value = element.getAttribute(name) ?? ''
              return [name, translatableFrenchText.has(value) ? value : '']
            })))
          }
          const originals = originalAttributes.get(element)!
          Object.entries(originals).forEach(([name, value]) => {
            if (value) element.setAttribute(name, translations[language][value] ?? value)
          })
        })
      }
    }

    translateTree(document.body)
    const observer = new MutationObserver((mutations) => mutations.forEach((mutation) => {
      mutation.addedNodes.forEach(translateTree)
      if (mutation.type === 'characterData') translateTree(mutation.target)
    }))
    observer.observe(document.body, { childList: true, subtree: true, characterData: true })
    return () => observer.disconnect()
  }, [language])
  const t = (text: string) => translations[language][text] ?? (language === 'fr' ? text : translations.en[text]) ?? text
  return <I18nContext.Provider value={{ language, setLanguage, t }}>{children}</I18nContext.Provider>
}

// eslint-disable-next-line react-refresh/only-export-components -- hook is colocated with its Provider by design
export const useI18n = () => useContext(I18nContext)
